@IsTest
private class BotGetContactUsSubTypeOptionsHandlerTest {
   /* @IsTest
    static void botActionTest() {
        BotGetContactUsSubTypeOptionsHandler.BotInput botInput = new BotGetContactUsSubTypeOptionsHandler.BotInput();
        List<BotGetContactUsSubTypeOptionsHandler.BotInput> botInputs = new List<BotGetContactUsSubTypeOptionsHandler.BotInput>{botInput};
        botInput.record = new Contact_Us_SubType_Option__c(Id = fflib_IDGenerator.generate(Contact_Us_SubType_Option__c.SObjectType), Name = 'subtype name');

        List<BotGetContactUsSubTypeOptionsHandler.BotOutput> result = BotGetContactUsSubTypeOptionsHandler.getContactUsOptionIdAndNames(botInputs);

        System.assertEquals(1, result.size());
        BotGetContactUsSubTypeOptionsHandler.BotOutput output = result.get(0);
        System.assertEquals(botInput.record.Id, output.id);
        System.assertEquals(botInput.record.Name, output.name);
    }

    */
}