@IsTest
private class BotGetContactUsTypeOptionsHandlerTest {
    /*
    @IsTest
    static void botActionTest() {
        BotGetContactUsTypeOptionsHandler.BotInput botInput = new BotGetContactUsTypeOptionsHandler.BotInput();
        List<BotGetContactUsTypeOptionsHandler.BotInput> botInputs = new List<BotGetContactUsTypeOptionsHandler.BotInput>{botInput};
        botInput.record = new Contact_Us_Type_Option__c(Id = fflib_IDGenerator.generate(Contact_Us_Type_Option__c.SObjectType), Name = 'type name');

        List<BotGetContactUsTypeOptionsHandler.BotOutput> result = BotGetContactUsTypeOptionsHandler.getContactUsOptionIdAndNames(botInputs);

        System.assertEquals(1, result.size());
        BotGetContactUsTypeOptionsHandler.BotOutput output = result.get(0);
        System.assertEquals(botInput.record.Id, output.id);
        System.assertEquals(botInput.record.Name, output.name);
    }

     */
}